# Generated by Django 4.1.7 on 2023-05-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
